-- Steuerprofil primary + partner fields (Hilfsmittel)
ALTER TABLE "User" ADD COLUMN "anrede" TEXT;
ALTER TABLE "User" ADD COLUMN "vorname" TEXT;
ALTER TABLE "User" ADD COLUMN "nachname" TEXT;
ALTER TABLE "User" ADD COLUMN "geburtsdatum" TEXT;
ALTER TABLE "User" ADD COLUMN "steuernummer" TEXT;
ALTER TABLE "User" ADD COLUMN "idNr" TEXT;
ALTER TABLE "User" ADD COLUMN "religion" TEXT;
ALTER TABLE "User" ADD COLUMN "street" TEXT;
ALTER TABLE "User" ADD COLUMN "zip" TEXT;
ALTER TABLE "User" ADD COLUMN "city" TEXT;
ALTER TABLE "User" ADD COLUMN "hasEmploymentIncome" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "hasSelfEmployment" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "hasCapitalIncome" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "partnerAnrede" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerVorname" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerNachname" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerGeburtsdatum" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerSteuernummer" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerIdNr" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerDifferentAddress" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "partnerStreet" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerZip" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerCity" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerReligion" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerSteuerklasse" TEXT;
ALTER TABLE "User" ADD COLUMN "partnerHasEmployment" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "partnerHasSelfEmployment" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "partnerHasCapitalIncome" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "partnerHasRentalIncome" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "partnerIsCrossBorder" BOOLEAN NOT NULL DEFAULT false;
